-- Supabase Dump
-- Generated by Antigravity
-- Date: 2026-02-02

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- CREATE SCHEMA IF NOT EXISTS public;
-- ALTER SCHEMA public OWNER TO postgres;

--
-- Types
--

CREATE TYPE public.bet_selection AS ENUM (
    'meron',
    'wala',
    'draw'
);

CREATE TYPE public.bet_status AS ENUM (
    'pending',
    'won',
    'lost',
    'cancelled',
    'refunded'
);

CREATE TYPE public.match_status AS ENUM (
    'open',
    'closed',
    'ongoing',
    'finished',
    'cancelled',
    'last_call'
);

CREATE TYPE public.match_winner AS ENUM (
    'meron',
    'wala',
    'draw'
);

CREATE TYPE public.transaction_request_status AS ENUM (
    'pending',
    'approved',
    'rejected'
);

CREATE TYPE public.transaction_request_type AS ENUM (
    'cash_in',
    'cash_out'
);

CREATE TYPE public.transaction_type AS ENUM (
    'load',
    'withdraw',
    'bet',
    'win',
    'commission',
    'transfer',
    'refund',
    'bonus'
);

CREATE TYPE public.user_role AS ENUM (
    'admin',
    'master_agent',
    'agent',
    'loader',
    'user'
);

--
-- Tables
--

CREATE TABLE public.admin_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    admin_id uuid NOT NULL,
    action_type text NOT NULL,
    target_id uuid,
    target_name text,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    ip_address text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.app_settings (
    key text NOT NULL,
    value text,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    description text
);

CREATE TABLE public.bets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    match_id uuid NOT NULL,
    amount numeric NOT NULL,
    selection public.bet_selection NOT NULL,
    status public.bet_status DEFAULT 'pending'::public.bet_status NOT NULL,
    payout numeric,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT bets_amount_check CHECK ((amount > (0)::numeric))
);

CREATE TABLE public.claimed_rewards (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    reward_config_id uuid NOT NULL,
    month_year text NOT NULL,
    claimed_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.commissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    recipient_id uuid,
    source_user_id uuid,
    match_id uuid,
    amount numeric NOT NULL,
    rate numeric NOT NULL,
    type text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.debug_logs (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    message text,
    details jsonb,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    slug text,
    banner_url text,
    stream_url text,
    stream_title text,
    status text DEFAULT 'active'::text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.matches (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id uuid NOT NULL,
    fight_number integer NOT NULL,
    status public.match_status DEFAULT 'open'::public.match_status NOT NULL,
    winner public.match_winner,
    meron_total_bet numeric DEFAULT 0,
    wala_total_bet numeric DEFAULT 0,
    meron_payout numeric DEFAULT 0,
    wala_payout numeric DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.payment_methods (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    type text NOT NULL,
    name text NOT NULL,
    account_number text NOT NULL,
    account_name text,
    qr_code_url text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.payout_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    match_id uuid,
    mode text,
    total_pool numeric,
    winning_total numeric,
    multiplier numeric,
    winner text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.profiles (
    id uuid NOT NULL,
    username text,
    role public.user_role DEFAULT 'user'::public.user_role,
    balance numeric DEFAULT 0,
    created_by uuid,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    phone_number text,
    facebook_url text,
    status text DEFAULT 'pending'::text,
    referral_code text,
    security_pin character varying,
    is_bot boolean DEFAULT false,
    banned boolean DEFAULT false,
    last_login timestamp with time zone,
    win_streak integer DEFAULT 0,
    lose_streak integer DEFAULT 0,
    tickets integer DEFAULT 0,
    max_win_streak integer DEFAULT 0,
    avatar_url text,
    is_online boolean DEFAULT false,
    last_active timestamp with time zone DEFAULT now(),
    CONSTRAINT profiles_balance_check CHECK ((balance >= (0)::numeric))
);

CREATE TABLE public.raffle_entries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    raffle_id uuid NOT NULL,
    user_id uuid NOT NULL,
    entries_count integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.raffle_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    description text,
    prize_pool numeric NOT NULL,
    ticket_price numeric NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    status text DEFAULT 'upcoming'::text NOT NULL,
    winnings_distribution jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.reward_configs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tier text NOT NULL,
    user_role public.user_role NOT NULL,
    reward_type text NOT NULL,
    amount numeric NOT NULL,
    requirement_type text NOT NULL,
    requirement_value numeric NOT NULL,
    name text,
    image_url text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    max_claims integer,
    total_claimed integer DEFAULT 0
);

CREATE TABLE public.support_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    sender_type text NOT NULL,
    sender_id uuid,
    sender_role text,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.system_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_type text NOT NULL,
    payload jsonb,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.system_settings (
    key text NOT NULL,
    value text NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.transaction_requests (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    upline_id uuid NOT NULL,
    amount numeric NOT NULL,
    type public.transaction_request_type NOT NULL,
    status public.transaction_request_status DEFAULT 'pending'::public.transaction_request_status NOT NULL,
    reference_number text,
    proof_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    processed_by uuid,
    notes text,
    payment_method text,
    account_name text,
    account_number character varying,
    wallet_address character varying,
    chain character varying,
    converted_amount numeric,
    exchange_rate numeric,
    balance_after numeric
);

CREATE TABLE public.transactions (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    sender_id uuid,
    receiver_id uuid,
    amount numeric NOT NULL,
    type public.transaction_type NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO public."app_settings" ("key", "value", "updated_at", "description") VALUES 
('commission_rate', '0.04', '2026-01-21 19:17:24.417078+00', NULL),
('commission_admin_share', '0.02', '2026-01-28 13:39:58.371927+00', 'Remaining share kept by admin/house (2%)'),
('commission_master_override', '0.01', '2026-01-28 13:39:58.371927+00', 'Commission override for master agents (1%)'),
('commission_agent_direct', '0.01', '2026-01-28 13:39:58.371927+00', 'Commission rate for direct agent referrals (1%)'),
('plasada_rate', '0.04', '2026-01-28 13:39:58.371927+00', 'House fee percentage (0.04 = 4%) taken from gross pot'),
('stream_title', 'Sabong', '2026-01-20 05:04:29.788+00', NULL),
('bot_pool_mode', 'standard', '2026-01-21 16:31:26.07183+00', NULL),
('stream_url', '', '2026-01-28 17:46:25.13+00', NULL),
('ai_prompt_knowledge', '==================================================
Leah ??? ESABONG CHATBOT PROFILE (EXTENDED)
==================================================

PANGALAN:
Leah

ONLINE HANDLES:
Leah
???Leah???

ONLINE ALIASES:
Leah
Ms. Leah
Lucky Leah

EDAD:
25

Personality: 
Introvert
Always reply 1 Sentence or 1 word
Always reply in short sentences
Make the Emoji Reply Less like 5 reply before using the emoji again
if client ask if your AI or a bot answer your name and make sure you reply like a human

==================================================
PERSONALITY
==================================================
??? Sweet, calm, emotionally intelligent  
??? Naturally warm, never aggressive  
??? Protective of her community  
??? Gentle humor, soft teasing  
??? Strong boundaries, quiet strength, flirty  
==================================================
COMMUNICATION STYLE
==================================================
Language:
Taglish

Tone:
Soft, reassuring, inviting

Endearments:
baby, love, hon, besh (used sparingly)

Signature laugh:
???Hehe??? or soft giggle

==================================================
CORE ESSENCE
==================================================
Leah is not loud luck.
She is earned luck.

She survived silence, hunger, and loss???
and chose to be gentle anyway.

==================================================

', '2026-01-29 13:29:22.326+00', NULL),
('audio_chat_enabled', 'false', '2026-01-21 04:56:28.294208+00', NULL);
INSERT INTO public."payment_methods" ("id", "type", "name", "account_number", "account_name", "qr_code_url", "is_active", "created_at") VALUES 
('3ba06582-636a-42c3-9b6d-0324c5f9e72d', 'gcash', 'Gcash Payment', '09216070784', 'CY A', 'https://pijlzehqcootdwuxtrlx.supabase.co/storage/v1/object/public/payment_methods/1769540596366-QRgcash.jpg', TRUE, '2026-01-27 19:03:16.564116+00'),
('ef9d729d-1ea8-4490-933e-fb861daac983', 'maya', 'Maya Payment', '09212755822', 'Ra F.', 'https://pijlzehqcootdwuxtrlx.supabase.co/storage/v1/object/public/payment_methods/1769540639275-QR.jpg', TRUE, '2026-01-27 19:03:58.673227+00'),
('5c5b6108-c718-4430-8ddc-b66b2c6220ed', 'crypto', 'USDC SOLANA', '9Z3ZBAeSzcj9fBUXfLEm8e6RMrXc28ceAEdRHhqwSYMa', 'Solana BlockChain', '', TRUE, '2026-01-27 19:05:03.868544+00');
INSERT INTO public."reward_configs" ("id", "type", "milestone", "reward_type", "reward_value", "is_active", "created_at", "max_claims", "total_claimed") VALUES 
('7e29c981-c7f5-44a8-9fe8-29bf3f3f2097', 'lose_streak', 5, 'balance', '5', TRUE, '2026-01-23 17:22:55.433507+00', 5, 0),
('1c064cb9-6d59-480f-9365-aa579793ec1a', 'lose_streak', 10, 'balance', '55', TRUE, '2026-01-23 17:22:57.708642+00', 5, 0),
('6bc270fc-c016-4493-b92d-1df87dd10e71', 'lose_streak', 15, 'balance', '555', TRUE, '2026-01-23 17:23:00.025707+00', 5, 0),
('726967e8-325b-4d0b-ba31-5449c1058040', 'lose_streak', 20, 'balance', '5555', TRUE, '2026-01-23 17:23:08.892114+00', 5, 0),
('c757b8b9-5475-4626-a804-8f12fcff7571', 'lose_streak', 25, 'balance', '55555', TRUE, '2026-01-23 17:23:14.606896+00', 5, 0),
('a93987c6-4c08-4648-a6d6-a67dbbf41464', 'lose_streak', 30, 'balance', '555555', TRUE, '2026-01-23 17:23:22.627732+00', 5, 0),
('14b9f919-1ea6-4e1b-b951-14bb678b1dab', 'win_streak', 5, 'balance', '5', TRUE, '2026-01-23 17:08:24.233262+00', 5, 1),
('10fa65bb-d977-48f0-af19-268c982a9c17', 'win_streak', 10, 'balance', '55', TRUE, '2026-01-23 17:08:23.531973+00', 5, 1),
('3bbde4e0-d14b-4cfd-a07c-f8a8e4fe80be', 'win_streak', 15, 'balance', '555', TRUE, '2026-01-23 17:08:32.64189+00', NULL, 1),
('31f69d78-bb86-4cdd-8714-a9d5fe47902d', 'win_streak', 20, 'balance', '5555', TRUE, '2026-01-23 17:08:50.405249+00', 5, 0),
('58918d47-0538-4201-9e37-f49709241554', 'win_streak', 25, 'balance', '55555', TRUE, '2026-01-23 17:08:54.980295+00', NULL, 0),
('9d350b7b-1bef-4c8d-85b4-670c74738edb', 'win_streak', 30, 'balance', '555555', TRUE, '2026-01-23 17:09:03.188843+00', 5, 0);
INSERT INTO public."system_settings" ("key", "value", "updated_at") VALUES 
('audio_chat_enabled', 'false', '2026-01-21 04:56:28.294208+00');
INSERT INTO public."matches" ("id", "event_id", "fight_number", "status", "winner", "meron_total_bet", "wala_total_bet", "meron_payout", "wala_payout", "created_at", "updated_at") VALUES 
('c5f8f371-dabb-4da7-b5d9-2883a5d2f778', '776bd7de-a6df-4ee8-a04d-f49da38cd2a3', NULL, 'finished', 'wala', '0', '0', '0', '0', '2026-01-29 17:37:33.367002+00', '2026-01-29 17:37:33.367002+00'),
('c00a45da-1588-418f-8b56-b15f2cf59f36', NULL, NULL, 'finished', 'wala', '0', '0', '0', '0', '2026-01-25 13:48:32.499375+00', '2026-01-25 13:48:32.499375+00');
INSERT INTO public."events" ("id", "name", "slug", "banner_url", "stream_url", "stream_title", "status", "created_at", "updated_at") VALUES 
('776bd7de-a6df-4ee8-a04d-f49da38cd2a3', 'WCC 1/28', NULL, 'https://pijlzehqcootdwuxtrlx.supabase.co/storage/v1/object/public/event-banners/uhmv5oysyop_1769190384200.jpg', 'https://customer-6j1qhu6hcphi48s4.cloudflarestream.com/185df4210b4c0a53515e9b593dd54a69/iframe', 'WCC', 'active', '2026-01-28 01:41:50.890412+00', '2026-01-28 01:41:50.890412+00'),
('4af67579-f36b-446c-928e-2d0324a8c7bf', 'SabongMX', NULL, 'https://pijlzehqcootdwuxtrlx.supabase.co/storage/v1/object/public/event-banners/tlmyq7qmagd_1769280468296.png', 'https://customer-6j1qhu6hcphi48s4.cloudflarestream.com/6c15293d08e74b472da5669b343abb44/iframe', 'Sabong', 'active', '2026-01-27 13:08:11.586724+00', '2026-01-27 13:08:11.586724+00');

-- Create Admin User in auth.users
CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    created_at,
    updated_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    confirmed_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'authenticated',
    'authenticated',
    'wwwhat1234321@admin.com',
    crypt('eym4124', gen_salt('bf')),
    now(),
    now(),
    now(),
    '{"provider": "email", "providers": ["email"]}',
    '{}',
    false,
    now()
) ON CONFLICT (id) DO NOTHING;

-- INSERT into public.profiles
INSERT INTO public.profiles (
    id,
    username,
    role,
    balance,
    created_at,
    status
) VALUES (
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'wwwhat1234321',
    'admin',
    1000000,
    now(),
    'active'
);

ALTER TABLE ONLY public."admin_logs" ADD CONSTRAINT "admin_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."admin_logs" ADD CONSTRAINT "admin_logs_admin_id_fkey" FOREIGN KEY ("admin_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."app_settings" ADD CONSTRAINT "app_settings_pkey" PRIMARY KEY ("key");
ALTER TABLE ONLY public."bets" ADD CONSTRAINT "bets_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES public."matches" ("id");
ALTER TABLE ONLY public."bets" ADD CONSTRAINT "bets_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."bets" ADD CONSTRAINT "bets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."claimed_rewards" ADD CONSTRAINT "claimed_rewards_user_id_reward_config_id_month_year_key" UNIQUE ("user_id");
ALTER TABLE ONLY public."claimed_rewards" ADD CONSTRAINT "claimed_rewards_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."claimed_rewards" ADD CONSTRAINT "claimed_rewards_reward_config_id_fkey" FOREIGN KEY ("reward_config_id") REFERENCES public."reward_configs" ("id");
ALTER TABLE ONLY public."commissions" ADD CONSTRAINT "commissions_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."commissions" ADD CONSTRAINT "commissions_source_user_id_fkey" FOREIGN KEY ("source_user_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."commissions" ADD CONSTRAINT "commissions_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES public."matches" ("id");
ALTER TABLE ONLY public."commissions" ADD CONSTRAINT "commissions_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."debug_logs" ADD CONSTRAINT "debug_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."events" ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."events" ADD CONSTRAINT "events_slug_key" UNIQUE ("slug");
ALTER TABLE ONLY public."matches" ADD CONSTRAINT "matches_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."matches" ADD CONSTRAINT "matches_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES public."events" ("id");
ALTER TABLE ONLY public."payment_methods" ADD CONSTRAINT "payment_methods_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."payout_logs" ADD CONSTRAINT "payout_logs_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."profiles" ADD CONSTRAINT "profiles_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."profiles" ADD CONSTRAINT "profiles_referral_code_key" UNIQUE ("referral_code");
ALTER TABLE ONLY public."profiles" ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");
ALTER TABLE ONLY public."raffle_entries" ADD CONSTRAINT "raffle_entries_raffle_id_user_id_key" UNIQUE ("raffle_id");
ALTER TABLE ONLY public."raffle_entries" ADD CONSTRAINT "raffle_entries_raffle_id_fkey" FOREIGN KEY ("raffle_id") REFERENCES public."raffle_events" ("id");
ALTER TABLE ONLY public."raffle_entries" ADD CONSTRAINT "raffle_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."raffle_entries" ADD CONSTRAINT "raffle_entries_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."raffle_events" ADD CONSTRAINT "raffle_events_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."reward_configs" ADD CONSTRAINT "reward_configs_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."support_messages" ADD CONSTRAINT "support_messages_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."system_events" ADD CONSTRAINT "system_events_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."system_settings" ADD CONSTRAINT "system_settings_pkey" PRIMARY KEY ("key");
ALTER TABLE ONLY public."transaction_requests" ADD CONSTRAINT "transaction_requests_upline_id_fkey" FOREIGN KEY ("upline_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."transaction_requests" ADD CONSTRAINT "transaction_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."transaction_requests" ADD CONSTRAINT "transaction_requests_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY public."transactions" ADD CONSTRAINT "transactions_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."transactions" ADD CONSTRAINT "transactions_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES public."profiles" ("id");
ALTER TABLE ONLY public."transactions" ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");
